import type { Metadata } from "next"
import "../scss/common.scss"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  authors: undefined,
  //추후 수정
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body>
        <div className="wrap">{children}</div>
      </body>
    </html>
  )
}
